### ISSUE TITLE
Watchman

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#101]
https://github.com/researchart/rose6icse/tree/master/submissions/available/Watchman
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/Watchman
https://github.com/researchart/rose6icse/tree/master/submissions/replicated/Watchman
https://github.com/researchart/rose6icse/tree/master/submissions/reproduced/Watchman

Contact Author
---
- Ying Wang
  - email: wangying@swc.neu.edu.cn
  - affiliation: Northeastern University
  - github id: NeolithEra

Authors
---
- Ying Wang
  - email: wangying@swc.neu.edu.cn
  - affiliation: Northeastern University
  - github id: NeolithEra
  
- Ming Wen
  - email: mwenaa@hust.edu.cn
  - affiliation: Huazhong University of Science and Technology
  - github id: justinwm
  
- Yepang Liu
  - email: liuyp1@sustech.edu.cn
  - affiliation: Southern University of Science and Technology
  - github id: yepangliu
  
- Yibo Wang
  - email: wyb_neu@163.com
  - affiliation: Northeastern University
  
- Zhenming Li
  - email: lzm_neu@163.com 
  - affiliation: Northeastern University
  
- Chao Wang
  - email: wangc_neu@163.com
  - affiliation: Northeastern University
  
- Hai Yu
  - email: yuhai@mail.neu.edu.cn
  - affiliation: Northeastern University
  
- Shing-Chi Cheung
  - email: scc@cse.ust.hk
  - affiliation: The Hong Kong University of Science and Technology
  - github id: sccust
  
- Chang Xu
  - email: changxu@nju.edu.cn
  - affiliation: Nanjing University
  
- Zhiliang Zhu
  - email: ZHUZhiLiang_NEU@163.com
  - affiliation: Northeastern University

## Note to reviewers: these authors want multiple badges
- reusable
- available
- replicated
- reproduced

**Comment by gh-artifact-1763** [comment]
@NeolithEra @timm @minkull Thanks for applying for the (rare) reproduced/replicated badges. For reproduced, you have attached [2 reports](https://github.com/researchart/rose6icse/blob/master/submissions/reproduced/Watchman/Reproduction%20report.pdf) from companies that used Watchman on their own code. That certainly seems to fit the criteria from the CFP:
> a subsequent study by a person or team other than the authors, without the use of author-supplied artifacts.

My hesitation would be that the 2 reproductions are not in academic venues and are not easily accessible. My understanding of the badge was that this paper had other *research* reproducing its findings with new data. 

On the other hand, the report seems to demonstrate that the tool results can be broadly reproduced, i.e., your theory that Watchman can quickly detect PyPi DC issues (and those issues are relevant to practitioners). Insisting on an academic paper for reproducibility seems to be a trifle silly when the main claimed result is a (scalable/usable) tool.

CCing the chairs in case they want to weigh in.

**Comment by artifacts-reviewer** [comment]
I have reviewed the artifact and have some comments on how the readme and install files could be improved: 

The README says the artifact contains data up to 31 Dec, 2020. Do you mean 2019? Note this date is listed more than once in the README and other files. 

date set -> dataset 

The README jumps right into using Watchman without explaining how to setup / start Watchman. Adding a simple line to say the user should go to the online Watchman tool with the link, click on the go button prior to noting anything about the diagnosis tab would be useful. 

The install file tells the reader to download Replaying evolution history.zip from Watchman's homepage (http://www.watchman-pypi.com/history), to reproduce the results. The README tells the reader to download Watchman, Watchman.zip, is available at http://www.watchman-pypi.com/artifacts. Watchman.zip contains the replaying evolution history.zip, but this is not clear on the install page. This could cause the reader to download the data more than once. 

The install file should provide setup instructions. When running the first scripts, I obtained: Traceback (most recent call last): File "validity_evaluation_period1.py", line 3, in <module> import pymysql ModuleNotFoundError: No module named 'pymysql' The install file should clearly explain what modules to install. Note I had to install pymysql, requests, and DBUtils. I now see the dependencies are listed as a note after explaining how to run the scripts, but the setup with explicit install instructions should be listed first. 

The install file says python 3 should be used, but the command shows python not python3. I used python3 and it worked. Please clarify. 

Note I did not let the script finish running since it is noted to take 3 to 4 days, but the early output did replicate what was expected. 

The install file only provides explicit instructions for replication of 5.1. Instructions should also be provided here in sufficient detail for section 5.2. 

It is not clear how one would use Watchman to analyze new data. Can the README file be updated to better explain how I could import my own data to analyze? 

Overall, the reader needs to switch between the README and install files frequently. It would be useful if the information between these two files was better structured. Do not duplicate information between the files, just refer to the other file if needed.

**Comment by artifacts-reviewer** [comment]
I also agree it would be good for the chairs to weigh in about the suitability of the replication/reproduction badges. It does seem companies were able to use Watchman.

**Comment by artifacts-reviewer** [comment]
Regarding the available and reusable badges, I suggest the authors upload all files to an online archive like Zenodo or Figshare after changes have been made to obtain a DOI.

**Comment by NeolithEra** [comment]
@artifacts-reviewer Many thanks for your careful and constructive comments! Following your suggestions, we accordingly revised and updated our Watchman’s [README](https://github.com/NeolithEra/rose6icse/blob/master/submissions/reproduced/Watchman/README.md) and [INSTALL](https://github.com/NeolithEra/rose6icse/blob/master/submissions/reproduced/Watchman/INSTALL.md) files (awaiting for the PRs being approved). We describe our revisions below.

- In the README file, we added an explanation at the beginning of the “A quick start to Watchman” Section:
**_“First, please visit the online Watchman tool via its link (http://www.watchman-pypi.com/). Its "DIAGNOSIS" page provides the main function.”_**

- To avoid possible misunderstanding to users of repetitively downloading the `Replaying evolution history.zip` package, we removed its link (http://www.watchman-pypi.com/history) from the INSTALL file, and added the following explanation:
**_“Inside the Watchman.zip package (for its download link, please refer to the README file), we provide the `Replaying evolution history.zip`, which contains all necessary materials for reproducing the results of Section 5.1.”_**

- For better understanding, we moved the clarification for installing the four Python packages in the running environment to the beginning of the setup instruction in the INSTALL file.

- Regarding the command of executing our scripts, since users’ local environments may have already installed other versions of Python (such as Python 2.\*), we added a note in the INSTALL file:
**_“Note that, if your local environment already has other versions of Python installed (such as Python 2.\*), it is fine but please make sure that command "`python`" would run python version 3.7.4.”_**
**_Explanation:_** “`python3`” is an official command in the Linux environment for running Python 3*, while our recommended running environment for Watchman is Windows 10 with python 3.7.4. Therefore, users may need to configure their environment variables to make sure that command "`python`" would run python 3.7.4, if their local environments have already installed other versions of Python.

- In the revised INSTALL file, we provided explicit instructions for verifying the results of Section 5.2.

-  In the revised README file, we provided more detailed explanations for clarifying how to import the data of Python projects to be analyzed (see Figures 2(a), 2(b), and 3, and the provided video demo at https://youtu.be/3EOz9g3Bw70).

- To reduce redundancy, we removed those descriptions appearing in both the README and INSTALL files, and reorganized the contents in them.

-  We reapplied for a DOI on Zenodo for the revised version of our artifacts and updated the DOI in our README file: **_https://zenodo.org/record/3668451_**




@gh-artifact-1763 
Thank you again for your great efforts on evaluating Watchman! We appreciate your constructive comments for helping Watchman towards the replicated and reproduced badges ^_^.

**Comment by timm** [comment]
I thank @artifacts-reviewer for their careful review of the artifacts themselves-- and the authors careful response to those comments. 

@artifacts-reviewer : with the above changes, can you now declare for "reusable" and "available"?

@gh-artifact-1763 : replicated means someone else has used the same tools to do "it" and reproduced means someone else has found the same results using different methods (e.g. a different codebase). given that, can you   make conform your decision   for "reusable" and "available"?

**Comment by artifacts-reviewer** [comment]
Available and reusable: The authors made all requested changes, so I believe these badges should be approved.

Replicated: There is a replication report available, but it is not published or peer-reviewed. I am hesitant to award the replicated badge.

Reproduced: There is a reproduction report which shows emails from two open source developers who used the Watchman tool and reported that it worked well. Again, this is not published or peer-reviewed, so I am hesitant to award the reproduced badge.

**Comment by NeolithEra** [comment]
@artifacts-reviewer
Thanks a lot for your feedback.

We have published the replication/reproduction reports on Zenodo. The DOI is 10.5281/zenodo.3668451. Or you may find them following the link https://zenodo.org/record/3668451.

We have questions about the criteria of “replicated” and “reproduced”.  From the conference website (https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions), seems that there are no clear requirements on the subsequent study that replicates/reproduces the original authors’ work. Does the study need to be published or peer reviewed? Are there any implicit requirements that are not listed on the website?

We would appreciate it if the chairs and reviewers could clarify.

Thank you very much.

**Comment by timm** [comment]
Thank your for clarifications

We have read the report .pdf docs in your Watchman.zip and while we thank you for that effort, these reports do not constitute a validated R&R (the repduction report, in particular is very brief).

Hence we will grant you the available and reusable badges.

Thank your for you contributions to ICSE artifacts 2020

**Comment by gh-artifact-1763** [comment]
@timm I humbly suggest that future instances of Artifacts make the R&R badging criteria more clear, because I think the authors of this submission did make an effort, and to some extent the directions are misleading. Making it clear the Replication is independent, and academic, would be helpful.

**Comment by NeolithEra** [comment]
@gh-artifact-1763 Thanks for your comments and understanding.
@timm Thanks for your feedback and explanation.

We indeed carefully prepared this artifacts, including improving the performance of Watchman, inviting other SE researchers for replications, applying our tool to industrial projects,  promoting the website of Watchman and trying to find 162 more real bugs in the open source commnunity. 
We prepared this artifact for more than three months.

We feel sorry for misunderstanding the criteria for artifact evalution.
We confirm our tool and experimental results can be replicated and reproduced, but the documents which are not available, cannot provide sufficient evidences.

Maybe it is difficult for our conference paper that is just accepted, to be replicated by other researchers in a published/peerreviewed paper in such a short time (from the date of paper being accepted to the date of artifact evaluation).

Thanks again for your efforts.
Ying
