### ISSUE TITLE
stringSolversTests

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#123]
https://github.com/researchart/rose6icse/tree/master/submissions/available/stringSolversTests

Authors:
* Alexandra Bugariu: alexandra.bugariu@inf.ethz.ch, Github id: [alebugariu](https://github.com/alebugariu)
* Peter MÃŒller: peter.mueller@inf.ethz.ch, Github id: [mueller55](https://github.com/mueller55)

Alexandra Bugariu is the corresponding author.

# applying for the Reusable and Available

**Comment by happyanonymous** [comment]
I suggest the authors to follow the instructions below when preparing the artifact:

"If the artifact contains or requires the use of a special tool or any other non-trivial piece of software the authors must provide a VirtualBox VM image or a Docker container image with a working environment containing the artifact and all the necessary tools. Note that we expect that the artifacts will have been vetted on a clean machine before submission."  from https://github.com/researchart/icse20

As of now, I do not see a VM or Docker available on the artifact page to facilitate the setup of the environment. From the artifact repository (here https://github.com/alebugariu/StringSolversTests), I would say that the artifact indeed falls in the category of requiring "the use of a special tool or any other non-trivial piece of software"

**Comment by alebugariu** [comment]
Thank you very much for your feedback. I added the Docker container and the corresponding instructions:
https://github.com/alebugariu/StringSolversTests 
https://github.com/alebugariu/rose6icse/blob/master/submissions/available/stringSolversTests/INSTALL.md
 I also created a pull request.

**Comment by happyanonymous** [comment]
Thank you very much for the additional material.

I am inclined to give the tags *Available* and *Reusable* (provided that the authors can provide a unique DOI along with the tool). 

I could successfully run the tool via the Docker container and the documentation of the material is very thorough.

Nevertheless, I'd like to report an exception that I found after running the `./run.sh -testSMT -prior` command (see image below). Please, let me know if you would like more details to reproduce the bug. I'm on a Windows 10 machine using Docker version 18.03.0-ce, build 0520e24302

![image](https://user-images.githubusercontent.com/44096371/74488279-9081d200-4f26-11ea-987e-c7bee0b0e5b2.png)

**Comment by alebugariu** [comment]
Thanks a lot for your feedback and for reporting the crash. Unfortunately I was not able to reproduce it. I ran the experiment on Windows 10 Pro (version 10.0.10586), using Docker version 18.03.0-ce, build 0520e24302 and everything worked fine (the tool printed the statistics in the end, and no exception was raised). I also tried on Ubuntu 16.04 (with and without the Docker container) and on macOS Catalina 10.15.3 (both with and without the container). I couldn't see the crash in any of the cases.

The exception you observed can happen if the solver generates a model that does not fulfill the expected format: ``<variable_name> <variable_value>``. This wasn't the case in any of the experiments I ran so far, but we did observed that the Z3str3 solver has sometimes non-deterministic behavior. We also know that there were multiple bugs in the implementation of the ```indexOf``` operation in Z3str3 4.7.1 (the prior version in our experiments). My impression is that this crash is due to non-determinism in Z3str3's decision procedure for handling ```indexOf```. So I will continue running the experiments on Windows, hoping that I will be able to reproduce this bug, then I will update our code accordingly.

Regarding the DOI, our artifact is now on Zenodo: [![DOI](https://zenodo.org/badge/235884734.svg)](https://zenodo.org/badge/latestdoi/235884734) 
I also made a pull request to include the DOI in the README and STATUS files.

**Comment by timm** [comment]
@happyanonymous has given permission for "reusable" and "available" (given the DOI now exists).

@grumpyreviewer : I look forward to your review.

**Comment by timm** [comment]
@grumpyreviewer : I look forward to your review.

**Comment by grumpyreviewer** [comment]
Ok with awarding _reusable_ and _available_ (now that a doi has been acquired).

I managed to run quite a few hours of experiments without observing the exception reported by my fellow reviewer (tried on both Mac and Linux). However, since the authors pointed our a reasonable cause for such exception, a small refactoring of the code could help reporting a more informative error when the solver returns a model in the wrong format.

Two other minor comments:
- please consider adding your Dockerfile to the repo (and the archived artifact on zenodo if possible): it acts as "enhanced" installation documentation and may help reuse, since a few changes to the file would make an adapted docker ready to use for different purposes (besides enabling builds and staged builds also in case you decide to remove your current image from dockerhub)
- [very minor] add chmod +x /StringSolversTests/run.sh in the Dockerfile

**Comment by minkull** [comment]
Reusable+Available awarded.

**Comment by alebugariu** [comment]
Thank you very much for your comments and suggestions. Based on your feedback, I've made the following changes:
- I've updated the code, to inform the user if the solver generated a model in an unexpected format. 
- I've added the [Dockerfile](https://github.com/alebugariu/StringSolversTests/blob/master/Dockerfile) to the repository  (chmod +x run.sh is now done automatically).
