### ISSUE TITLE
theosotrPuppet

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#125]
https://github.com/researchart/rose6icse/tree/master/submissions/available/theosotrPuppet
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/theosotrPuppet

* Thodoris Sotiropoulos (theosotr@aueb.gr), theosotr (Corresponding author)
* Dimitris Mitropoulos (dimitro@aueb.gr), dimitrop
* Diomidis Spinellis (dds@aueb.gr), dspinellis

## Note to reviewers: these authors want multiple badges
- available
- reusable

**Comment by AnAnonymousReviewer** [comment]
Dear authors, 

I do not have a Unix system available. Could you please create the Docker image for me so that I can run and test under Windows? 

Best regards
AnAnonymousReviewer

**Comment by theosotr** [comment]
Dear reviewer @AnAnonymousReviewer 

Running our instructions on a Cygwin environment should work under Windows.
Please let me know if you have any other difficulties on building our Docker image.

**Comment by theosotr** [comment]
@AnAnonymousReviewer alternatively, you could run our instructions on a `git-bash` terminal inside your  Windows environment.

**Comment by timm** [comment]
@theosotr  
- does this use windows GUI stuff? or could @AnAnonymousReviewer run in the windows bash command without Cygwin? please advise.

**Comment by theosotr** [comment]
The reviewers can run this from a git-bash terminal because one step requires the execution of a bash script.
A git-bash terminal should be OK as it comes with the installation of git and provides the basic Unix commands.

**Comment by minkull** [comment]
@andromeda04 looking forward to your reviews

**Comment by AnAnonymousReviewer** [comment]
Dear authors, 

I have made progress yesterday, but I am stuck at a new point. 

I built the docker file under Windows PowerShell successfully (i.e. no error message, just a warning (*)). I cannot run it, as I get 

"docker run -ti --rm  --security-opt seccomp:unconfined fsmove
standard_init_linux.go:211: exec user process caused "no such file or directory". 

I have also tried to run docker in Git Bash (using th eimage buuilt under Windows PowerShell), but get the following error: 
"$ docker run -ti --rm  --security-opt seccomp:unconfined fsmove
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'"

I'll now try to build the docker image using Git Bash. If you have any suggestions for me in the meantime, please let me know. 

Let me add that I used "docker build -t fsmove --build-arg IMAGE_NAME=debian:stretch ." to build the docker image. This resulted in a security warning "SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host.", but I guess that should not cause the problem. 

Best regards
AnAnonymousReviewer

P.S. Building in Git Bash did not help (it actually did not rebuild, as it ran much to quick, will also try from a fresh clone). Using winpty as mentioned in the Git Bash error also does not help, I then get the same error as in Windows PowerShell: 
"$ winpty docker run -ti --rm --security-opt seccomp:unconfined fsmove
standard_init_linux.go:211: exec user process caused "no such file or directory" "

P.P.S.: I ran "docker build -t fsmove --build-arg IMAGE_NAME=debian:stretch ." in Git Bash, but that also does not help. It was again much quicker than the initial build in Windows PowerShell, but the reason for the longer build seems to be that it first had to download the necessary dependencies. 

I have two warning-like messages in the initial build: 
"debconf: delaying package configuration, since apt-utils is not installed"
"WARNING: apt does not have a stable CLI interface. Use with caution in scripts."

I am attaching the anonymized logs of  the two build attempts. The first log is incomplete as I just copied it from Windows PowerShell and it seems to have cut the topmost lines. 

[build log 2020-02-16 Windows PowerShell.txt](https://github.com/researchart/rose6icse/files/4213466/build.log.2020-02-16.Windows.PowerShell.txt)
[build log 2020-02-17 Git Bash.txt](https://github.com/researchart/rose6icse/files/4213467/build.log.2020-02-17.Git.Bash.txt)

P.P.S.: I found hints online that the error "standard_init_linux.go:211: exec user process caused "no such file or directory" " can be fixed by using Linux Line endings. So I replaced all Windows line endings (CR LF) with Unix ones (LF) in all files below the folder fsmove, in particular in "process-module.sh", and in the scripts in "fsmove-eval\scripts\". Still, the error message persists. 

Maybe the first few lines of "process-module.sh" are already a problem, as these directories are not available on my system (esp. the hard coded /etc/ directory)? 

"basedir=${HOME}/data
modulepath=${HOME}/.puppet/etc/code/modules
install_module="no"
timeout=6
with_strace=0
iterations=1
production_dir=/etc/puppet/code/environments/production"

I have no further ideas what to try. Please advise!

**Comment by theosotr** [comment]
Dear @AnAnonymousReviewer 
> 
> 
> Dear authors,
> 
> I have made progress yesterday, but I am stuck at a new point.
> 
> I built the docker file under Windows PowerShell successfully (i.e. no error message, just a warning (*)). I cannot run it, as I get
> 
> "docker run -ti --rm --security-opt seccomp:unconfined fsmove
> standard_init_linux.go:211: exec user process caused "no such file or directory".
>

Please, consider changing the last line of `Dockerfile` to `ENTRYPOINT ["bash", "process-module.sh"]` as pointed by this [answer](https://stackoverflow.com/a/51719411).

> Maybe the first few lines of "process-module.sh" are already a problem, as these directories are not available on my system (esp. the hard coded /etc/ directory)?
> 
> "basedir=${HOME}/data
> modulepath=${HOME}/.puppet/etc/code/modules
> install_module="no"
> timeout=6
> with_strace=0
> iterations=1
> production_dir=/etc/puppet/code/environments/production"
>

No, this is not a problem at all, because these paths correspond to paths specified inside the container, not the host machine. Note that the `process-module.sh` script runs inside the container, not your host machine.

If the above does not work, please let me know to prepare a Virtualbox VM running Linux.

**Comment by AnAnonymousReviewer** [comment]
After changing the last line in "dockerfile" to "ENTRYPOINT ["bash", "process-module.sh"]", I still get the error "standard_init_linux.go:211: exec user process caused "no such file or directory" " (both in Git Bash and in Windows PowerShell).

If you could provide a Virtualbox VM running linux, that would be great. I also had trouble running an Ubuntu from a USB stick on my Microsoft Surface (which is probably not the best machine to run Linux on...). Also, I could not readily create a Virtualbox VM with the Ubuntu ISO file I downloaded earlier (but did not investigate further what goes wrong).

**Comment by theosotr** [comment]
Thank you.
I am currently preparing a VirtualBox VM for you. I will inform you when it's ready.

**Comment by theosotr** [comment]
@AnAnonymousReviewer 

* I have prepared a VirtualBox VM running Ubuntu 18.04. You can download it from this [link](https://drive.google.com/open?id=104-t1BXXdSM8sJi-pr-_OMrOaxvQGs-Y).

* <del>This VM contains the `fsmove-eval` repo inside the home directory (i.e. `/home/user`). Also, I have built the docker image for you, so that you can proceed to the next steps of the artifact. However if you want to built the Docker image on your own you can delete it by running `sudo docker rmi fsmove`</del>.

* VM details: `username`: user and `password`: user

* Finally, I created a PR (See [here](https://github.com/researchart/rose6icse/pull/175)) where I have added the instructions for Windows users.

**Comment by theosotr** [comment]
I have updated the VirtualBox VM so that it does not contain the pre-built Docker Images.

Also, note that I sucessfully ported the VirtualBox VM from a Windows machine.

**Comment by AnAnonymousReviewer** [comment]
Thanks! I will try it now. 

P.S.: It turns out that I could not create a virtual box VM myself yesterday because I also have Docker installed (for a different artefact). I initially also was not able to start your VM, but now, it seems, I found a [solution for that](https://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx).

**Comment by theosotr** [comment]
> Thanks! I will try it now.
> 
> P.S.: It turns out that I could not create a virtual box VM myself yesterday because I also have Docker installed (for a different artefact). I initially also was not able to start your VM, but now, it seems, I found a [solution for that](https://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx).

@AnAnonymousReviewer, so did you manage to run the VM and install the Docker image?

**Comment by AnAnonymousReviewer** [comment]
Yes, thanks. It works and I will be inspecting the results next (but might not manage to do so today). I was able to run the mysql example and the alertlogic example so far and it looks good.

**Comment by andromeda04** [comment]
The authors apply for the reusable and available badges.

====reusable====

After see all the installation problems with the Docker image, I tried the tool in a Unix system. The installation of the tool was successful! I tried all the examples provided by the authors. I also run the benchmarks, Everything worked well, and the analysis results are clearly summarized in a file (faults.csv). The result is consistent with what the authors claimed.

**So, I recommend the “reusable” badge.**

====available====

The artifact is publicly available at Github (https://github.com/theosotr/fsmove-eval) under the GNU general public license v3.0. The authors also released it on Zenodo and provided a DOI ( https://doi.org/10.5281/zenodo.3627895). 

**So, I also recommend the “available” badge.**

**Comment by timm** [comment]
Since @andromeda04 reported success, I'm marking the reusable and available.  

Thank you to all reviewers for their efforts.

**Comment by JonDoe-ArtifactsTrack** [comment]
Settings:
- ova image given by the author.


Following the instruction given by the authors i was able to install,, build and run the project and also to run all examples (example1, example2) and also the benchmarks and trace dataset.  

it is closed but just wanted to confirm that i agree with the decision made.

**Comment by AnAnonymousReviewer** [comment]
As I already was almost done with my review, I am also adding it here. Note that I did not check the aspect "consistency" of "functional" in detail yet. But as the fellow reviewer have already done so, I will leave that be. 

The authors ask for the badges "reusable" and "available" for their toolfsmove that analyzes Puppet specifications for mistakes. Both badges have the criteria of the level "functional" as preconditions. I am using the criteria from [1] and [2]. 

In the following, I will discuss the criteria for these badges. 


= Functional= 

* "Documented: At minimum, an inventory of artifacts is included, and sufficient description provided to enable the artifacts to be exercised."
 
The documentation to run the tool is complete. I was able to install and run the tool using a clean Linux VM. So yes. 

* "Consistent: The artifacts are relevant to the associated paper, and contribute in some inherent way to the generation of its main results."

I did not check in detail. 

* "Complete: To the extent possible, all components relevant to the paper in question are included. (Proprietary artifacts need not be included. If they are required to exercise the package then this should be documented, along with instructions on how to obtain them. Proxies for proprietary data should be included so as to demonstrate the analysis.)"

All required dependencies were available and I was able to run the tool, so yes.

* "Exercisable: Included scripts and/or software used to generate the results in the associated paper can be successfully executed, and included data can be accessed and appropriately manipulated."

The instructions at https://github.com/researchart/rose6icse/blob/master/submissions/available/theosotrPuppet/README.md  were sufficient to generate the results. --> yes

Running the benchmarks with "./scripts/run-benchmarks.sh" required sudo privileges. 

--> The artifact seems to be functional, but I did not check the consistency in detail 


= Available = 

* "placed on a publicly accessible archival repository. A DOI or link to this repository along with a unique identifier for the object is provided."

--> The artifact is available at https://doi.org/10.5281/zenodo.3627895, so yes. 

= Reusable = 

* "The artifacts associated with the paper are of a quality that significantly exceeds minimal functionality. That is, they have all the qualities of the Artifacts Evaluated – Functional level, but, in addition, they are very carefully documented and well-structured to the extent that reuse and repurposing is facilitated. In particular, norms and standards of the research community for artifacts of this type are strictly adhered to."

The artifact's source code is additionally available at https://github.com/theosotr/fsmove-eval and https://github.com/AUEB-BALab/fsmove. I checked a few classes and found sufficient documentation, so that it seems to be possible for other researchers to reuse and repurpose it. Also, additional documentation on the usage of the tool in general is provided.  

--> yes, "reusable". 

[1] https://conf.researchr.org/track/icse-2020/icse-2020-Artifact-Evaluation#Call-for-Submissions
[2] https://www.acm.org/publications/policies/artifact-review-badging

**Comment by theosotr** [comment]
@AnAnonymousReviewer, @andromeda04 and @JonDoe-icse20Artifacts thank you for your reviews!
