### ISSUE TITLE
mathewSLACC

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#131]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/mathewSLACC

## Authors
* Corresponding author &rarr; George Mathew - **Email**: [george2@ncsu.edu](mailto:george2@ncsu.edu); **Github**: [bigfatnoob](github.com/bigfatnoob)
* Chris Parnin - **Email**: [cjparnin@ncsu.edu](mailto:cjparnin@ncsu.edu); **Github**: [chrisparnin](github.com/chrisparnin)
* Kathryn T Stolee - **Email**: [ktstolee@ncsu.edu](mailto:ktstolee@ncsu.edu); **Github**: [kstolee](github.com/kstolee)

@ applying for reusable

**Comment by gorocketsgo** [comment]
The authors apply for the REUSABLE badge. I followed the instructions in README.md and INSTALL.md but run into several issues.

***Load the pre-configured VirtualBox image***
I tried to load the image on Ubuntu 14.04 and macOS Mojave but run into the same problem (see the error image below). Both machines have installed the latest VirtualBox (6.1.2).
<img width="513" alt="vm-load-error" src="https://user-images.githubusercontent.com/49999621/74122040-ce35d200-4b97-11ea-8a8d-347949d0612d.png">

***Build from scratch***
When running `pip install -r requirements.txt`, I got a permission issue but it's easy to fix using `sudo`. But when running the `sh scripts/common/initialize.sh` to initialize the database, I got the following error and was not able to fix it.

> [2020-02-09 23:46:10,242] [WARNING] [mongo_driver.py] Dataset 'Example' does not exist. Creating this mongo manually and rerun the application. Don't forget to insert dummy record
Traceback (most recent call last):
  File "store/init_db.py", line 32, in <module>
    clear_db(args[1])
  File "store/init_db.py", line 14, in clear_db
    db = mongo_driver.get_dataset_db(dataset)
  File "/SLACC/code/src/main/python/store/mongo_driver.py", line 55, in get_dataset_db
    raise RuntimeError(e)
RuntimeError: Looks like client is down

**Comment by github-anonymous** [comment]
### Reusable Badge (reject):
I was not able to run the tool.

### Option #1 VirtualBox image
INSTALL.MD
The image does not start, probably due to the guest MAC OS and non-MAC host hardware. The error screen is shown below.

![virtualbox-error](https://user-images.githubusercontent.com/57346494/74535396-0477a680-4f36-11ea-998b-d6ee13af8fd3.png)

### Option #2 from scratch (I’m using an x64 Ubuntu 18.04.3 LTS)
INSTALL.MD
Cannot install python requirements via command `pip install -r requirements.txt`
Several C libraries are missing, the error log is attached in install-error.txt
I fixed that by installing apt-packages ` libreadline-dev r-base-dev`.
$MONGO_HOME is unclear what should be stated, mongod is running and reachable.

[install-error.txt](https://github.com/researchart/rose6icse/files/4204626/install-error.txt)


README.MD
I skipped step 1 as it is optional and I want to check included dataset Example at first.
Step 2: `scripts/common/initialize.sh Example` seems to run fine, the log is attached in initialize.txt

[initialize.txt](https://github.com/researchart/rose6icse/files/4204628/initialize.txt)

I chose step 3 instead of 4 because I want to run all stages for dataset Example.

Step 3: `scripts/common/runner.sh Example` produces several errors, the log is attached in runner-error.txt

[runner-error.txt](https://github.com/researchart/rose6icse/files/4204629/runner-error.txt)

Finally, step 5 is not verifiable by me. There are no results as files or in the database.

**Comment by timm** [comment]
@bigfatnoob 
@chrisparnin
@kstolee 

looks like the artifact has a permission bug. can you fix asap?

**Comment by bigfatnoob** [comment]
### Virtual Machine not booting
Thank you for pointing out the problems with the virtual machine instance. As noted by @github-anonymous, the problem was due to the difference in guest and host OS when using MacOSX.   I have now reconfigured it to run on Ubuntu 18.04. The link to the image is in the [same folder](https://drive.google.com/drive/u/3/folders/1UqWRvwiSy9ILwFMEDC6_bimzP2mg9m_T). The credentials are the same as well
```
Username: SLACC
Password: slacc
```

Please note that the database must be started before initialization or running SLACC on a dataset. On the virtual machine, the database can be started using
```
> sudo systemctl start mongod 
```

### Trouble in installing dependencies
There was a python package that needed `r-base-dev`. This package is optional and we have now removed it. 

### Building from scratch
@gorocketsgo found that the initialization phase failed and raised the error
```
[2020-02-09 23:46:10,242] [WARNING] [mongo_driver.py] Dataset 'Example' does not exist. Creating this mongo manually and rerun the application. Don't forget to insert dummy record
Traceback (most recent call last):
File "store/init_db.py", line 32, in
clear_db(args[1])
File "store/init_db.py", line 14, in clear_db
db = mongo_driver.get_dataset_db(dataset)
File "/SLACC/code/src/main/python/store/mongo_driver.py", line 55, in get_dataset_db
raise RuntimeError(e)
RuntimeError: Looks like client is down
```
I presume this is because the database was not running.

### Error while running `scripts/common/runner.sh`.
@github-anonymous notes that `sh scripts/common/runner.sh Example` produces several errors. Thank you for providing the necessary logs for debugging. This was because SLACC requires the `mongod` service to be running as a daemon. I have updated [INSTALL.md](https://github.com/DynamicCodeSearch/SLACC/blob/ICSE20/INSTALL.md#navigating-around) to highlight this and the necessary command to run mongo as a daemon.

**Comment by timm** [comment]
@gorocketsgo 
@github-anonymous : please review this new pull request

**Comment by github-anonymous** [comment]
I can now run the program but I cannot reproduce the results.

### Option 1: VirtualBox image (updated)
I’m able to run the commands `sh scripts/common/initialize.sh CodeJam` and `sh scripts/common/runner.sh CodeJam`.
There are 4 files created in `meta_results/CodeJam/clusters/cluster_testing/eps_0.01/` as mentioned in README.MD step 5, but they are empty.
Also, there are no directories or files for other thresholds, e.g., 0.05, 0.10, 0.15, 0.20, 0.25, 0.30

I’m able to run the same commands for the `Example` dataset and get correct-looking results for various thresholds.

The logs are attended.

Even with correct results, it is somewhat unclear to me where these are used/reproduced in the paper.
Section 4.3 mentions a threshold of 1.0, but there are only thresholds up to 0.3 in the outputs. No explicit thresholds are given for Tables 4 and 5.
Where is the differentiation between valid and invalid clusters (Table 4) or False Positives (Table 5)?

[runner-codejam.txt](https://github.com/researchart/rose6icse/files/4226925/runner-codejam.txt)
[initialize-codejam.txt](https://github.com/researchart/rose6icse/files/4226926/initialize-codejam.txt)

**Comment by bigfatnoob** [comment]
@github-anonymous 
Thank you for running the tool and posting the logs :)

### Error in executing `CodeJam`
Based on the logs, it looks like `initialize` was successfully run but the `runner` failed in multiple phases. This is common for a large dataset like `CodeJam` and you might need to run each phase independently, as pointed out in ReadMe.md. Further using the virtual machine might not be optimum as it might require around 32 GB (at least 16GB) of RAM to be completed in a reasonable amount of time. It might be best to set it to use [Option 2(Setting up from scratch)](https://github.com/DynamicCodeSearch/SLACC/blob/ICSE20/INSTALL.md#setting-up-from-scratch). Due to this, we provided an `Example` dataset to demonstrate the functionality.

That said, intermediate files were created in the VM and the java and python parser was trying to parse it which raised the exception. I have updated the source code and the repository to address this issue. I have also updated the VM.

### Regarding results
>There are 4 files created in meta_results/CodeJam/clusters/cluster_testing/eps_0.01/ as mentioned in README.MD step 5, but they are empty. Also, there are no directories or files for other thresholds, e.g., 0.05, 0.10, 0.15, 0.20, 0.25, 0.30

This is due to the error in the runner. 
 
> Section 4.3 mentions a threshold of 1.0, but there are only thresholds up to 0.3 in the outputs. 

The tool uses `tolerance threshold(eps)`, which is roughly `1 -similarity threshold` which is used in the paper. The clusters are generated for a tolerance threshold of 0.01, 0.05, 0.10,0.15,0.2, 0.25 and 0.3. In our paper, we use the similarity of 1.0 (tolerance of 0.01) since we did not have enough space to document the impact of this hyper-parameter.

> No explicit thresholds are given for Tables 4 and 5. Where is the differentiation between valid and invalid clusters (Table 4) or False Positives (Table 5)?

* Table 4 is generated by post-processing the clusters with more randomly generated arguments(10 times) to identify false positives.
* Table 5 is generated by varying the `\#_Executions` from 8 to 256 and rerunning the clusters. This parameter can be adjusted in `Settings.java` and rerun to get new clusters for lesser number of inputs.
* Since these scripts required post-processing, manual verification and consumed a lot of time, we did not post them in the repository.

Thank you :)

**Comment by gorocketsgo** [comment]
Thanks for preparing a new VM image. Now I can successfully open it in VirtualBox.

I tested the tool using the `Example` dataset. All scripts run successfully, both when running all stages at once or separately. I inspected the generated clusters of semantic clones. The results look correct. Therefore, I think this tool is functional with a clear demo.

I am not able to reproduce the results on the CodeJam dataset since I don't have 32GB RAM in my machine and it also takes a long time to finish. Providing some pre-computed results for inspection would be helpful.

@bigfatnoob You mentioned about `similarity threshold` and `tolerance threshold`. Their distinction is not very clear. Can you explicitly document these two parameters in the README? Can you also add instructions about how to config these two parameters in the tool? Currently, all details a user needs to know about your tool are capsulated in those python scripts. Providing more details about how to config and run the tool itself is helpful to make it more reusable.

Right now the artifact provides clear instructions and scripts to run the tool on two existing datasets. However, it is not clear how to run the tool on a new dataset (e.g., new python and Java projects downloaded from GitHub). Can I just pass the file path of the new dataset to the `initialize.sh` script? Does it need any pre-configuration? I suggest the authors add explicit instructions about how to reuse your tool on a new code corpus. 

I will recommend the REUSABLE badge for the tool if the authors add explicit instructions about 1) the configurable parameters of this tool and how to config them and 2) how to reuse the tool on a new dataset.

**Comment by bigfatnoob** [comment]
@gorocketsgo 
Thank you for the comments and your proposed changes. I will make them immediately and include additional details in the README file. :)

**Comment by minkull** [comment]
@gorocketsgo agrees with reusable subject to authors' revisions.
@github-anonymous please could you let us know your views?

@bigfatnoob we will need the revisions asap to reach a decision.

**Comment by bigfatnoob** [comment]
I've submitted a [pull request](https://github.com/researchart/rose6icse/pull/197) based on your suggested changes. This PR includes
* [Configuring SLACC](https://github.com/DynamicCodeSearch/SLACC/blob/ICSE20/README.md#configuring-slacc)
* [Setting up new datasets](https://github.com/DynamicCodeSearch/SLACC/blob/ICSE20/README.md#new-datasets)
* [Difference](https://github.com/DynamicCodeSearch/SLACC/blob/ICSE20/README.md#d-cluster)  between `similarity_threshold` and `tolerance_threshold`

**Comment by gorocketsgo** [comment]
Thanks @bigfatnoob These changes look good to me. I recommend the REUSABLE badge for this artifact.

**Comment by timm** [comment]
@github-anonymous 

our preliminary decision, pending your input, is "reusable". 

but please CONFIRM or VETO that preliminary decision as you see fit

**Comment by github-anonymous** [comment]
Hi Tim,
I CONFIRM the decision.
