### ISSUE TITLE
peiming-XRust

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#134]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/peiming-XRust

Peiming Liu, Texas A&M University, peiming@tamu.edu
Gang Zhao, Texas A&M University, zhaogang92@tamu.edu
Jeff Huang, Texas A&M University, jeff@cse.tamu.edu

# Applying for reusable badge.

**Comment by ICSE20ArtifactAnonymousReviewer** [comment]
The authors apply for the badge *reusable*.

Reusable: The artifact is functional and easy to install and run. 

Unfortunately, the source code does not seem to be available. Furthermore, there is no detailed documentation of what exactly is where in the docker container. That seems to limit reusability.
Besides that, I would also propose to add a note to the instructions about the expected duration of running the benchmark.

License (ok): The license is MIT.

**Comment by PeimingLiu** [comment]
Hi, Thank you so much for your careful review.

To clarify, the docker image contains **all the source code** for the modified XRust compiler as well as the source code for all the benchmarks listed in the paper. All under the `/ICSE` folder. We will add more descriptions.

We are actually in the progress of making a public the github source as well, but since we modified the Rust compiler and add keywords to it, it makes the bootstrapping process of the XRust compiler very complicated. The toolchain of Rust also changed dramatically since our modification, so it will take us sometimes to figure out the dependency of XRust (as it is built upon previous version of Rust compilers).

Finally, thanks for the suggestions for providing information about the expected duration! We will attach our results in the paper for reference!


***********************
We updated our readme for the docker image. It now contains a detailed description of what contains in the docker image (https://hub.docker.com/repository/docker/geticliu/xrust-icse2020)

Also, the source code for XRust on Github can be obtained from https://github.com/PeimingLiu/XRust.

Please let us know if there is any more concerns! Thanks again for your careful reviews!

**Comment by ICSE20ArtifactAnonymousReviewer** [comment]
Hi, 
Thank you for the clarification. It is correct that the source code in available on the docker image.
Thank you for updating the docker image's readme and adding a link to the github repository.
Kind regards

**Comment by timm** [comment]
@ICSE20ArtifactAnonymousReviewer  just to check: you are now agreeing to "reusable"? Or..?

@JonDoe-icse20Artifacts : looking forward to your review.

**Comment by PeimingLiu** [comment]
Please also let me know if there is anything I can do!

Thanks!
Peiming Liu

**Comment by ICSE20ArtifactAnonymousReviewer** [comment]
@timm, yes I do.

**Comment by timm** [comment]
So currently we are at "reusable"=yes and am awaiting confirm or veto from @JonDoe-icse20Artifacts

**Comment by JonDoe-ArtifactsTrack** [comment]
Thank you for your submission. 
I have executed the version that has been updated by @PeimingLiu following to comments made by @ICSE20ArtifactAnonymousReviewer.
The artifacts are now functional and are also carefully documented and structured. Indeed i was able to reuse and execute the benchmark that authors define. 

I think we can give the Reusable badge to this artifact now.

**Comment by minkull** [comment]
Both reviewers recommend reusable.

**Comment by minkull** [comment]
Reusable awarded.
