### ISSUE TITLE
bpaulsen-ReluDiff

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#136]
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/bpaulsen-ReluDiff

Author List:

\*Brandon Pauslen, email: bpaulsen@usc.edu, github ID: pauls658

Jingbo Wang, email: jingbow@usc.edu, github ID: bobowang2223

Chao Wang, email: wang626@usc.edu, github ID: chaowang-vt

\* Corresponding Author

# applying for  Reusable

**Comment by timm** [comment]
@gorocketsgo @random-friendly-dude : I look forward to your reviews

**Comment by ai-sta-website** [comment]
Title: ReluDiff: Differential Verification of Deep Neural Networks [[repo](https://github.com/pauls658/ReluDiff-ICSE2020-Artifact)]
​
# Overall Summary
​
The artifact implemented the methods proposed by "ReluDiff: Differential Verification of Deep Neural Networks". The repo is well-documented to reproduce/reuse their work. Due to limited time, we reproduce some representative experiments in the given VM and inspect relevant codes. Generally, the artifact satisfies the specification of the "reusable" badge. We also present some suggestions to facilitate future improvements of "ReluDiff".
​
# Result
​
All experiments are done in the given VM (3 Cores, 4 GB Memory). We note that our time usage is somehow noticeably lower than the results in the paper.
​
## HAR
​
We run `run_HAR_exec-time_experiments.sh` and somehow failed to execute the last property, i.e., "1099", and it says "wrong input!". We then computed the accumulative time in log file which is 7.34s. All properties are proved besides "1099".
​
## MNIST
​
We tested 3-pixel perturbation on 2x512,3x100 and 4x1024 neural networks and skipped the global perturbation since it is too time-consuming.
​
|Benchmark | Verified Problem |  Total Time (s) |
|-|-|-|
|2x512 | 100 | 65.75 |
|3x100 | 100 | 16.00 |
|4x1024 | 100 | 248.67 |
​
## ACAS Xu
​
We executed `run_ACAS_exec-time_experiments.sh` and computed the accumulative time.
​
|Property | Verified Problem |  Total Time (s)|
|-|-|-|
|1 | 45 | 339.82 |
|3 | 42 | 54.67 |
|4 | 42 | 20.50 |
|5 | 1 | 5.25 |
|6 | 1 | 5.79 |
|7 | 1 | 3.98 |
|8 | 1 | 50.70 |
|9 | 1 | 5.92 |
|10 | 1 | 17.02 |
|11 | 1 | 1.31 |
|12 | 1 | 6.73 |
|13 | 1 | 19.10 |
|14 | 2 | 4.72 |
|15 | 2 | 14.60 |
​
# Documentation
​
The artifact is well-documented. The authors provide sufficient instructions for us to reproduce and reuse the work.
​
# Consistency
​
**As far as we tested**, all functionality are in line with what the authors stated in the paper. And, as is mentioned, the time usage is much lower than the results in paper.
​
# Extensibility
​
The artifact well meets the expectations in this paper, and users convert own models into ".nnet" format and verify given properties.
However, the property to verify is hard-coded in the code. Here, we encourage the authors to re-organize the codes and make the model "property" configurable for users.

# Badge 
As aforementioned, I believe the artifact satisfies the `reusable` badge.

**Comment by gorocketsgo** [comment]
This artifact includes 1) the source code of the proposed tool, ReluDiff, and its baselines, 2) the benchmark of 49 neural networks used in the evaluation, and 3) the scripts to compress a neural network for differential verification. The authors apply for the REUSABLE badge.  

The README file provides clear documentation about the source code files, which is useful for code inspection and adaptation. I used the VM image provided by the authors to try the tool and reproduce the experiments. I suggest the authors export the VirtualBox image to a single OVA file, rather than packaging the virtual hard disk and log files into a zip file. Because OVA can be used interchangeably between VMWare and VirtualBox. In addition, users do not have to manually create a new virtual machine and attach the virtual hard disk to it. 

The README file also elaborates on the functionality of each script as well as its arguments. Each script also displays a help menu if it is executed with no arguments. 

I tested the three scripts that use ReluDiff to verify ACAS property 6, a single MNIST image 3 pixel perturbed on the 3x100 network, and a single HAR input globally perturbed on the HAR network. The output of the first two scripts is consistent with the expected output in the README file. However, the third script shows there is no adversary (screenshot attached) while the README file says it will throw a segmentation fault on HAR due to unbounded recursion. Though I don't think this small issue will affect my ACCEPT decision, I wish the authors could clarify this inconsistency in the rebuttal and fix it.
![Screen Shot 2020-02-17 at 11 41 43 PM](https://user-images.githubusercontent.com/49999621/74705006-622f1b80-51e0-11ea-8350-6323351a41b8.png)

The results of the ReluVal on the previous three examples are consistent with the description in the README. 

Overall, I think this artifact is clearly documented and easy to use. Therefore, I think the REUSABLE badge is well deserved.
