### ISSUE TITLE
akondAcid

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#15]
Automated Categorizer for Infrastructure as Code Defects (ACID).

https://github.com/researchart/rose6icse/tree/master/submissions/available/akondACID
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/akondACID

- Akond Rahman, Tennessee Technological University, arahman@tntech.edu, GitHub ID: akondrahman 
- Effat Farhana, North Carolina State University, efarhan@ncsu.edu, GitHub ID: effat
- Chris Parnin, North Carolina State University, cjparnin@ncsu.edu, GitHub ID: chrisparnin
- Laurie Williams, North Carolina State University, williams@csc.ncsu.edu, GitHub ID:lauriew

Akond Rahman is the corresponding author.

## Note that the authors seek both an available and reusable badge

**Comment by unknown-user1234** [comment]
The authors apply for the Available and Reusable Badges.

**Available**: The code was made available in a repository and documentation regarding dawnloading, installation and the basic usage is provided. 

Decision: **Accept**

**Reusable**: Instructions on how to execute experiments reported in the paper are provided, however, there aren’t documentation on how to perform experiments on different files. In order to be reusable, the artifact must be, also, able to process different files than the used in the submitted work. 

Decision: **Reject**

**Comment by timm** [comment]
@JonDoe-icse20Artifacts : I look forward to your review.

**Comment by JonDoe-ArtifactsTrack** [comment]
The authors request for multiple badges. 
Available: the artifacts are placed in a publicly available and accessible repo. Also i was able to install and run the application by following the indications provided so it is also functional. As so i agree that the Available badge can be assigned. 

Reusable: means that the artifact is functional (and this is confirmed by the above assessment) plus it is very carefully documented and structured so that others can reuse the material. 
Now to my interpretation this does not mean that the authors of the artifact need to describe how to perform experiments on different files. They must assure that they have provided indications on to how to execute the experiments. 
I assume that reusable means that others can use the artifact material and apply it to their own experiments. 
from this interpretation i think we can assign the Reusable badge as well.

**Comment by akondrahman** [comment]
@timm : am I allowed to address comments from the first reviewer ?

**Comment by timm** [comment]
hey @akondrahman : thanks for submitting to this track. much appreciated!

right now we can badge "available"

but if you want "reusable", then YES you need to address those concerns

if you've sent a pull request, please advise here.

**Comment by minkull** [comment]
Many thanks everyone for your inputs.

No response from @akondrahman addressing @unknown-user1234's concerns on reusable.

Available badge awarded.
