### ISSUE TITLE
PAMDroid semi-automated approach to detect the misconfiguration of analytic services

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#28]
PAMDroid

https://github.com/researchart/rose6icse/tree/master/submissions/available/PAMDroid/
https://github.com/researchart/rose6icse/tree/master/submissions/available/PAMDroid/

- Xueling Zhang (corresponding author)
Email: xueling.zhang@utsa.edu
Github ID: 46972217
- Xiaoyin Wang
Email: Xiaoyin.Wang@utsa.edu
Github ID: 2389340
Rocky Slavin
Email: Rocky.Slavin@utsa.edu
Github ID: 1155845
- Travis Breaux
Email: breaux@cs.cmu.edu
Github ID: 8729372
- Jianwei Niu
Email: jianwei.niu@utsa.edu
Github ID:

# seeking an AVAILABLE badge

**Comment by timm** [comment]
I'm deleting the large subdirectories from your submission. 

scream if you need them back

**Comment by anonymous042** [comment]
This artifact relates to a semi-automated approach to detect the misconfiguration of analytic services. The submission does not provide a link to a repository or a zenodo entry.

Comments/Questions:
* LICENSE.md: OK
* CONTACT.md: OK
* In INSTALL.md, what are the prerequisites? (OS?, runtime? version?)
* 'app-analytic.xlsx': add direct link to the file
* Where is the source code of the Python code?
* Depending on hardware is an issue, could you provide a Docker image that runs the tool based on an emulated Android phone?

**Comment by icse2020review** [comment]
The following files are provided by the developers:
CONTACT.md,  STATUS.md, INSTALL.md, and LICENSE.md. 
The installation instructions are also properly given in detail. Yet the python source code is not available.

**Comment by timm** [comment]
artifact at least needs links to source code

**Comment by timm** [comment]
@anonymous042 and @icse2020review : I fear I've made your job harder. submission initially came with source code-- which I asked the authors to delete for size reasons

I'm sure they will soon be sending a pull request with the link

**Comment by minkull** [comment]
@46972217  over to you

**Comment by XuelingZhang19** [comment]
Source code and other supported files are available at https://github.com/XuelingZhang19/PAMDroid 

Pull request on updating readme.md has been sent too.

**Comment by timm** [comment]
@XuelingZhang19 : I had to block your pull request. see https://github.com/researchart/rose6icse/pull/185

**Comment by anonymous042** [comment]
Review updated based on https://github.com/XuelingZhang19/PAMDroid

Submission:
* LICENSE.md: OK
* CONTACT.md: OK

The repository https://github.com/XuelingZhang19/PAMDroid contains in particular:

* 3 python files
* 3 Excel sheets
* 11 apk files for testing
* 103 pdf files containing privacy policies.

The python files contain 40, 189 and 1763 lines respectively, the biggest one, `instrumentation.py` does not contain top-level documentation on how to use it, it is not referred to in README file.

`APP-Analytic.xlsx` contains the 1682 pairs (app name, analytic service), `Invocation_1000.xlsx` contains 5811 method calls, some of them with actual parameters, `PrivacyPolicyMisalignment.xlsx` contains the results of manualy analysis of policy problems by 3 annotators for 150 apps.

Comments:
* why is there a discrepancy between the folder name `PrivacyPolicies_120`, the number of PDFs in that folder (106) and the number of rows in `PrivacyPolicyMisalignment.xlsx` (150)?
* CSV/TSV files are better in a repository than XLSX because they can be versioned on a line basis and they can be browsed online
* We need a saved version of the 150 analyzed APK
* it is possible to run the tool based on an Android emulator, that would be awesome for reproducibility. It may actually run out of the box in a docker image.

**Comment by timm** [comment]
Current status: 

- cannot give "available" badge unless the authors update their submission

can this happen today/friday?

**Comment by XuelingZhang19** [comment]
-  1. PrivacyPolicies_120: we do not consider the apps that having a non-English privacy policy.

    PrivacyPolicyMisalignment.xlsx has 150 lines for 120 apps because some apps have more than one ASM invocation (see column C). 

-  2.some apk files are too big that GitHub does not allow uploading. You can find the 120 analyzed (instrumented) APK here: https://drive.google.com/drive/folders/1mqPQEjoBfjJ0Oxh1_cgkmEXnxZvjJl6Z?usp=sharing

- 3. Updated the CSV version. Please check https://github.com/XuelingZhang19/PAMDroid  

- 4. The tool could be run on an Android emulator. We choose a real device for the experiment because it has much better performance.

**Comment by timm** [comment]
@anonymous042   
@icse2020review  
we are currently at "no badge". but can you check @XuelingZhang19 's latest updates?

**Comment by anonymous042** [comment]
> https://drive.google.com/drive/folders/1mqPQEjoBfjJ0Oxh1_cgkmEXnxZvjJl6Z?usp=sharing

Avoid using perishable URL on Google Drive. The recommended solution is to push the data on 
Zenodo.

If this dataset is pushed on Zenodo, I'm OK with badge "available".

**Comment by minkull** [comment]
@XuelingZhang19 @icse2020review
Decision is currently "no badge", but this may still change by Monday depending on @icse2020review's view and on the dataset being pushed to Zenodo by @XuelingZhang19.

**Comment by XuelingZhang19** [comment]
We have uploaded the dataset into Zenodo. Please kindly check at: https://zenodo.org/record/3685312#.XlL8IS2ZPuR

**Comment by minkull** [comment]
Available will be awarded by 24th Feb AoE unless @anonymous042 @icse2020review shout otherwise by the end of 24th Feb AoE.

**Comment by minkull** [comment]
Many thanks everyone for the discussions!

Available awarded.
