### ISSUE TITLE
wenMemlock

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#5]
# received

https://github.com/researchart/rose6icse/tree/master/submissions/available/wenMemlock
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/wenMemlock

materials moved into subdirectory.

# Note to reviewers: these authors want multiple badges

- reusable
- available

**Comment by minkull** [comment]
# Author

```tex
\author{Cheng Wen}
\affiliation{
  \institution{CSSE, Shenzhen University}
  \city{Shenzhen}
  \country{China}}

\author{Haijun Wang}
\affiliation{
  \institution{CSSE, Shenzhen University}
  \city{Shenzhen}
  \country{China}}

\author{Yuekang Li}
\affiliation{
  \institution{Nanyang Technological University}
  \country{Singapore}}

\author{Shengchao Qin}
\affiliation{
  \institution{Teesside University}
  \city{Tees Vally}
  \country{UK}}

\author{Yang Liu}
\affiliation{
  \institution{Nanyang Technological University}
  \country{Singapore}}

\author{Zhiwu Xu}
\affiliation{
  \institution{CSSE, Shenzhen University}
  \city{Shenzhen}
  \country{China}}

\author{Hongxu Chen}
\affiliation{
	\institution{Nanyang Technological University}
	\country{Singapore}}

\author{Xiaofei Xie}
\affiliation{
	\institution{Nanyang Technological University}
	\country{Singapore}}

\author{Geguang Pu}
\affiliation{
	\institution{East China Normal University}
	\city{Shanghai}
	\country{China}}

\author{Ting Liu}
\affiliation{
  \institution{Xi'an Jiaotong University}
  \city{Xi'an}
  \country{China}}
```

**Comment by timm** [comment]
@JonDoe-icse20Artifacts  and @helpacksi : I look forward to your review

**Comment by JonDoe-ArtifactsTrack** [comment]
Thank you for your submission. 
authors request for Reusable Badge. 

Available: the tool is functional and placed on a publicly available repository. I have followed the indications provided by the authors of the package and step by step managed to correctly install the artifact and also execute it. No problems at all. So i agree that the Available badge should be given .

Reusable: means that the artifact is functional and carefully documented and structured so that others can easily reuse the material. As for this part, it is surely functional (verified in the previous step). Also, the authors of the artifact package did a very nice job as they have organized the material very clearly and provided several details useful for reproducing the results. As so, i agree that the Reusable badge should also be given.

**Comment by helpacksi** [comment]
Review: **Available and Reusable**

The submitted artifact is reusable. I was able to recreate the steps as provided by the authors. I was successfully able to run the tests provided by the author. 

I would however recommend that the authors provide instructions on how to compile and build MemLock on any arbitrary binary similar to that of AFL.
